# File Tree: aioon

**Generated:** 3/13/2026, 11:17:12 PM
**Root Path:** `c:\Users\Lenovo\OneDrive\Desktop\projects\aioon`

```
├── 📁 backend
│   ├── ⚙️ package-lock.json
│   ├── ⚙️ package.json
│   └── 📄 server.js
├── 📁 public
│   └── 🖼️ vite.svg
├── 📁 src
│   ├── 📁 assets
│   │   ├── 🖼️ Aioon_logo-01.png
│   │   ├── 🖼️ CRM.png
│   │   ├── 🖼️ ERP.png
│   │   ├── 🖼️ HR.jpg
│   │   ├── 🖼️ Robot.png
│   │   ├── 🖼️ ai&analytics.png
│   │   ├── 🖼️ ai.png
│   │   ├── 🖼️ compliance.png
│   │   ├── 🖼️ construction.jpg
│   │   ├── 🖼️ contact.png
│   │   ├── 🖼️ customer.png
│   │   ├── 🖼️ einvoice.png
│   │   ├── 🖼️ enterprise.png
│   │   ├── 🖼️ erp1.png
│   │   ├── 🖼️ payroll.png
│   │   ├── 🖼️ project.png
│   │   ├── 🖼️ react.svg
│   │   └── 🖼️ white logo aioon.png
│   ├── 📁 components
│   ├── 📄 AIAnalytics.jsx
│   ├── 📄 CRM.jsx
│   ├── 📄 Construction.jsx
│   ├── 📄 Contact.jsx
│   ├── 📄 EInvoicing.jsx
│   ├── 📄 ERP.jsx
│   ├── 📄 HR.jsx
│   ├── 📄 Services.jsx
│   ├── 🎨 index.css
│   ├── 📄 main.jsx
│   └── 📄 site.jsx
├── ⚙️ .gitignore
├── 📝 README.md
├── 📄 eslint.config.js
├── 🌐 index.html
├── ⚙️ package-lock.json
├── ⚙️ package.json
├── 📄 postcss.config.js
├── 📄 tailwind.config.js
└── 📄 vite.config.js
```

---
*Generated by FileTree Pro Extension*